  
baseURL: http://blog.shaokunxie.xyz
languageCode: en-us
title: MyNotebook
paginate: 10
assetDir: ./static

enableEmoji: true
hasCJKLanguage: true
permalinks:
  posts: /posts/:title/


markup:
  highlight:
    guessSyntax: true
    style: emacs
  goldmark:
    renderer:
      unsafe: true


social:
  # github: https://github.com/Shaokun-X
  # twitter: https://github.com/nodejh
  # stackoverflow: https://stackoverflow.com/users/4518882/nodejh


params:
  author: Shaokun XIE
  # bio: Software Engineer
  description: My very own notebook.
  enableRSS: true
  # enableComments: true
